FROM apache/airflow:2.9.3-python3.11

ENV AIRFLOW_HOME=/opt/airflow

COPY ./requirements/requirements-python.txt /

USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends vim 
  
USER airflow

ENV PATH="$HOME/.local/bin:$PATH"
RUN pip install -r /requirements-python.txt

WORKDIR $AIRFLOW_HOME