FROM apache/airflow:2.9.3-python3.11

ENV AIRFLOW_HOME=/opt/airflow

COPY ./requirements/requirements-python.txt /

USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends  vim git openssh-client \
  && groupadd -g 9999 sharedconfig \ 
  && usermod -aG sharedconfig airflow \
  && passwd -d airflow \
  && echo 'airflow ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/airflow \
  && chmod 0440 /etc/sudoers.d/airflow
  
USER airflow

ENV PATH="$HOME/.local/bin:$PATH"
RUN pip install -r /requirements-python.txt

WORKDIR $AIRFLOW_HOME